site_name: AWS Well-Architected Labs
site_description: 'A collection of AWS Well-Architected workshops'
site_url: 'https://wellarchitectedlabs.com'


# Repository
repo_name: 'awslabs/aws-well-architected-labs'
repo_url: 'https://github.com/awslabs/aws-well-architected-labs'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'


# Must use true for gh-deploy
#use_directory_urls: true

# Must use for /site builds
# NOTE: will break gh-deploy
use_directory_urls: false



theme:
    name: material
    feature:
        tabs: true
    custom_dir: 'theme'
    palette:
        primary: 'grey'
        accent: 'grey'
    logo: 'images/wa.png'

# https://github.com/awslabs/aws-well-architected-labs/issues/92
extra_css:
  - 'stylesheets/extra.css'

nav:
    - Home: README.md
    - Operational Excellence:
        - Overview: 'Operations/README.md'
        - 100 Inventory Patch Mgt:
            - Lab Overview: 'Operations/100_Inventory_and_Patch_Mgmt/README.md'
            - Lab Guide: 'Operations/100_Inventory_and_Patch_Mgmt/Lab_Guide.md'
    - Security:
        - Overview: 'Security/README.md'
        - Security 100 Labs:
            - Account and Root User:
                - Lab Overview: 'Security/100_AWS_Account_and_Root_User/README.md'
                - Lab Guide: 'Security/100_AWS_Account_and_Root_User/Lab_Guide.md'
            - Basic Identity & Access Management User, Group, Role:
                - Lab Overview: 'Security/100_Basic_Identity_and_Access_Management_User_Group_Role/README.md'
                - Lab Guide: 'Security/100_Basic_Identity_and_Access_Management_User_Group_Role/Lab_Guide.md'
            - CloudFront with S3 Bucket Origin:
                - Lab Overview: 'Security/100_CloudFront_with_S3_Bucket_Origin/README.md'
                - Lab Guide: 'Security/100_CloudFront_with_S3_Bucket_Origin/Lab_Guide.md'
            - Create a Data Bunker:
                - Lab Guide: 'Security/100_Create_a_Data_Bunker/README.md'
            - Enable Security Hub:
                - Lab Overview: 'Security/100_Enable_Security_Hub/README.md'
                - Lab Guide: 'Security/100_Enable_Security_Hub/Lab_Guide.md'
        - Security 200 Labs:
            - Automated Deployment of Detective Controls:
                - Lab Overview: 'Security/200_Automated_Deployment_of_Detective_Controls/README.md'
                - Lab Guide: 'Security/200_Automated_Deployment_of_Detective_Controls/Lab_Guide.md'
            - Automated Deployment of EC2 Web Application:
                - Lab Overview: 'Security/200_Automated_Deployment_of_EC2_Web_Application/README.md'
                - Lab Guide: 'Security/200_Automated_Deployment_of_EC2_Web_Application/Lab_Guide.md'
            - Automated Deployment of IAM Groups and Roles:
                - Lab Overview: 'Security/200_Automated_Deployment_of_IAM_Groups_and_Roles/README.md'
                - Lab Guide: 'Security/200_Automated_Deployment_of_IAM_Groups_and_Roles/Lab_Guide.md'
            - Automated Deployment of VPC:
                - Lab Overview: 'Security/200_Automated_Deployment_of_VPC/README.md'
                - Lab Guide: 'Security/200_Automated_Deployment_of_VPC/Lab_Guide.md'
            - Automated Deployment of Web Application Firewall:
                - Lab Overview: 'Security/200_Automated_Deployment_of_Web_Application_Firewall/README.md'
                - Lab Guide: 'Security/200_Automated_Deployment_of_Web_Application_Firewall/Lab_Guide.md'
            - Automated IAM User Cleanup:
                - Lab Overview: 'Security/200_Automated_IAM_User_Cleanup/README.md'
                - Lab Guide: 'Security/200_Automated_IAM_User_Cleanup/Lab_Guide.md'
            - Basic EC2 with WAF Protection:
                - Lab Overview: 'Security/200_Basic_EC2_with_WAF_Protection/README.md'
                - Lab Guide: 'Security/200_Basic_EC2_with_WAF_Protection/Lab_Guide.md'
            - CloudFront with WAF Protection:
                - Lab Overview: 'Security/200_CloudFront_with_WAF_Protection/README.md'
                - Lab Guide: 'Security/200_CloudFront_with_WAF_Protection/Lab_Guide.md'
        - Security 300 Labs:
            - IAM Permission Boundaries Delegating Role Creation:
                - Lab Overview: 'Security/300_IAM_Permission_Boundaries_Delegating_Role_Creation/README.md'
                - Lab Guide: 'Security/300_IAM_Permission_Boundaries_Delegating_Role_Creation/Lab_Guide.md'
            - IAM Tag Based Access Control for EC2:
                - Lab Overview: 'Security/300_IAM_Tag_Based_Access_Control_for_EC2/README.md'
                - Lab Guide: 'Security/300_IAM_Tag_Based_Access_Control_for_EC2/Lab_Guide.md'
            - Incident Response with AWS Console and CLI:
                - Lab Overview: 'Security/300_Incident_Response_with_AWS_Console_and_CLI/README.md'
                - Lab Guide: 'Security/300_Incident_Response_with_AWS_Console_and_CLI/Lab_Guide.md'
            - Lambda Cross Account IAM Role Assumption:
                - Lab Overview: 'Security/300_Lambda_Cross_Account_IAM_Role_Assumption/README.md'
                - Lab Guide: 'Security/300_Lambda_Cross_Account_IAM_Role_Assumption/Lab_Guide.md'
            - Lambda Cross Account Using Bucket Policy:
                - Lab Overview: 'Security/300_Lambda_Cross_Account_Bucket_Policy/README.md'
                - Lab Guide: 'Security/300_Lambda_Cross_Account_Bucket_Policy/Lab_Guide.md'
            - Incident Response Playbook with Jupyter:
                - Lab Overview: 'Security/300_Incident_Response_Playbook_with_Jupyter-AWS_IAM/README.md'
                - Lab Guide: 'Security/300_Incident_Response_Playbook_with_Jupyter-AWS_IAM/Lab_Guide.md'
        - Security Quests:
            - Introduction to Security: 'Security/Quest_100_Loft_Introduction_to_Security/README.md'
            - Quick Steps to Security Success: 'Security/Quest_100_Quick_Steps_to_Security_Success/README.md'
            - Incident Response Day: 'Security/Quest_200_Incident_Response_Day/README.md'
            - Security Best Practices Workshop: 'Security/Quest_300_Security_Best_Practices_Workshop_EC2/README.md'
            - Security Best Practices Day: 'Security/Quest_300_Security_Best_Practices_Day/README.md'
            - Managing Credentials and Authentication: 'Security/Quest_Managing_Credentials_and_Authentication/README.md'
            - Control Human Access: 'Security/Quest_Control_Human_Access/README.md'
            - Control Programmatic Access: 'Security/Quest_Control_Programmatic_Access/README.md'
            - Detect and Investigate Events: 'Security/Quest_Detect_and_Investigate_Events/README.md'
            - Defend Against New Threats: 'Security/Quest_Defend_Against_New_Threats/README.md'
            - Protect Networks: 'Security/Quest_Protect_Networks/README.md'
            - Protect Compute: 'Security/Quest_Protect_Compute/README.md'
            - Classify Data: 'Security/Quest_Classify_Data/README.md'
            - Protect Data at Rest: 'Security/Quest_Protect_Data_at_Rest/README.md'
            - Protect Data in Transit: 'Security/Quest_Protect_Data_in_Transit/README.md'
            - Incident Response: 'Security/Quest_Incident_Response/README.md'
    - Reliability:
        - Overview: 'Reliability/README.md'
        - 200 Testing Backup and Restore of Data:
            - Lab Overview: 'Reliability/200_Testing_Backup_and_Restore_of_Data/README.md'
            - Lab Guide: 'Reliability/200_Testing_Backup_and_Restore_of_Data/Lab_Guide.md'
        - 300 Health Checks and Dependencies:
            - Lab Overview: 'Reliability/300_Health_Checks_and_Dependencies/README.md'
            - Lab Guide: 'Reliability/300_Health_Checks_and_Dependencies/Lab_Guide.md'
        - Testing Resiliency:
            - 200 EC2 Resiliency:
                - Lab Overview: 'Reliability/200_Testing_for_Resiliency_of_EC2/README.md'
                - Lab Guide: 'Reliability/200_Testing_for_Resiliency_of_EC2/Lab_Guide.md'
            - 300 EC2, RDS S3 Resiliency:
                - Lab Overview: 'Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/README.md'
                - Lab Guide: 'Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/Lab_Guide.md'
                - Trouble Shooting Guide: 'Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/TroubleShooting_Guide.md'
    - Performance Efficiency:
        - Overview: 'Performance/README.md'
        - Monitoring with CloudWatch Dashboards: 'Performance/100_Monitoring_with_CloudWatch_Dashboards/README.md'

    - Cost Optimization:
        - Overview: 'Cost/README.md'
        - Fundamentals: 'Cost/Fundamentals.md'
        - Expenditure Awareness: 'Cost/ExpenditureAwareness.md'
        - Cost Effective Resources: 'Cost/CostEffectiveResources.md'
        - 100 Level Labs:
            - Account Setup:
                - Overview: 'Cost/Cost_Fundamentals/100_1_AWS_Account_Setup/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/100_1_AWS_Account_Setup/Lab_Guide.md'
            - Cost and Usage Governance:
                - Overview: 'Cost/Cost_Fundamentals/100_2_Cost_and_Usage_Governance/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/100_2_Cost_and_Usage_Governance/Lab_Guide.md'
            - Pricing Models:
                - Overview: 'Cost/Cost_Fundamentals/100_3_Pricing_Models/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/100_3_Pricing_Models/Lab_Guide.md'
            - Cost and Usage Analysis:
                - Overview: 'Cost/Cost_Fundamentals/100_4_Cost_and_Usage_Analysis/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/100_4_Cost_and_Usage_Analysis/Lab_Guide.md'
            - Cost and Usage Visualization:
                - Overview: 'Cost/Cost_Fundamentals/100_5_Cost_Visualization/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/100_5_Cost_Visualization/Lab_Guide.md'
        - 200 Level Labs:
            - Cost and Usage Governance:
                - Overview:  'Cost/Cost_Fundamentals/200_2_Cost_and_Usage_Governance/README.md'
                - Lab Guide:  'Cost/Cost_Fundamentals/200_2_Cost_and_Usage_Governance/Lab_Guide.md'
            - RI Analysis:
                - Overview: 'Cost/Cost_Fundamentals/200_3_Pricing_Models/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/200_3_Pricing_Models/Lab_Guide.md'
            - Savings Plan Analysis:
                - Overview: 'Cost/Cost_Effective_Resources/200_Pricing_Model_Analysis/README.md'
                - Lab Guide: 'Cost/Cost_Effective_Resources/200_Pricing_Model_Analysis/Lab_Guide.md'
            - Cost and Usage Analysis:
                - Overview: 'Cost/Cost_Fundamentals/200_4_Cost_and_Usage_Analysis/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/200_4_Cost_and_Usage_Analysis/Lab_Guide.md'
            - Cost and Usage Visualization:
                - Overview: 'Cost/Cost_Fundamentals/200_5_Cost_Visualization/README.md'
                - Lab Guide: 'Cost/Cost_Fundamentals/200_5_Cost_Visualization/Lab_Guide.md'
        - 300 Level Labs:
            - Automated CUR Updates and Ingestion:
                - Overview: 'Cost/Cost_and_Usage_Analysis/300_Automated_CUR_Updates_and_Ingestion/README.md'
                - Lab Guide: 'Cost/Cost_and_Usage_Analysis/300_Automated_CUR_Updates_and_Ingestion/Lab_Guide.md'
            - Multi Account CUR Access:
                - Overview: 'Cost/Cost_and_Usage_Analysis/300_Multi_Account_CUR_Access/README.md'
                - Lab Guide: 'Cost/Cost_and_Usage_Analysis/300_Multi_Account_CUR_Access/Lab_Guide.md'
            - Splitting Sharing CUR:
                - Overview: 'Cost/Cost_and_Usage_Analysis/300_Splitting_Sharing_CUR_Access/README.md'
                - Lab Guide: 'Cost/Cost_and_Usage_Analysis/300_Splitting_Sharing_CUR_Access/Lab_Guide.md'
            - Auto Financial CUR Reports:
                - Overview: 'Cost/Expenditure_Awareness/300_Automated_CUR_Query_and_Email_Delivery/README.md'
                - Lab Guide: 'Cost/Expenditure_Awareness/300_Automated_CUR_Query_and_Email_Delivery/Lab_Guide.md'


    - Well Architected Tool:
        - Overview: 'Well-ArchitectedTool/README.md'
        - Walkthrough:
            - Lab Overview: 'Well-ArchitectedTool/100_Walkthrough_of_the_Well-Architected_Tool/README.md'
            - Lab Guide: 'Well-ArchitectedTool/100_Walkthrough_of_the_Well-Architected_Tool/Lab_Guide.md'
